### ISSUE TITLE
Success dialog dismissTime throws exception

### ISSUE THREAD

**Issue by finger563** [bradmartin/nativescript-wear-os#11]
```
System.err: Error: java.lang.NoSuchMethodError: no non-static method "Landroid/animation/ValueAnimator;.setDuration()V"
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1070)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1050)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1042)
System.err:     com.permobil.smartdrive.MainActivity.onStart(MainActivity.java:35)
System.err:     android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
System.err:     android.app.Activity.performStart(Activity.java:7165)
System.err:     android.app.Activity.performRestart(Activity.java:7276)
System.err:     android.app.ActivityThread.handleSleeping(ActivityThread.java:4297)
System.err:     android.app.ActivityThread.access$2300(ActivityThread.java:200)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1750)
System.err:     android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     android.os.Looper.loop(Looper.java:193)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6680)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: File: "file:///data/data/com.permobil.smartdrive.wearos/files/app/vendor.js, line: 39293, column: 13
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'createDummyZeroDurationAnimator', file:'file:///data/data/com.permobil.smartdrive.wearos/files/app/vendor.js', line: 39293, column: 14
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/fragment.transitions.js.NoTransition.createAndroidAnimator', file:'file:///data/data/com.permobil.smartdrive.wearos/files/app/vendor.js', line: 39302, column: 16
System.err: 	Frame: function:'setupExitAndPopEnterAnimation', file:'file:///data/data/com.permobil.smartdrive.wearos/files/app/vendor.js', line: 39185, column: 35
System.err: 	Frame: function:'setupAllAnimation', file:'file:///data/data/com.permobil.smartdrive.wearos/files/app/vendor.js', line: 39197, column: 5
System.err: 	Frame: function:'_setAndroidFragmentTransitions', file:'file:///data/data/com.permobil.smartdrive.wearos/files/app/vendor.js', line: 38786, column: 9
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame.js.Frame._navigateCore', file:'file:///data/data/com.permobil.smartdrive.wearos/files/app/vendor.js', line: 40248, column: 32
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame-common.js.FrameBase.performNavigation', file:'file:///data/data/com.permobil.smartdrive.wearos/files/app/vendor.js', line: 39577, column: 14
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame-common.js.FrameBase._processNextNavigationEntry', file:'file:///data/data/com.permobil.smartdrive.wearos/files/app/vendor.js', line: 39568, column: 22
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame.js.Frame._processNextNavigationEntry', file:'file:///data/data/com.permobil.smartdrive.wearos/files/app/vendor.js', line: 40104, column: 58
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame-common.js.FrameBase.onLoaded', file:'file:///data/data/com.permobil.smartdrive.wearos/files/app/vendor.js', line: 39363, column: 14
System.err: 	Frame: function:'', file:'file:///data/data/com.permobil.smartdrive.wearos/files/app/vendor.js', line: 34640, column: 90
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper', file:'file:///data/data/com.permobil.smartdrive.wearos/files/app/vendor.js', line: 34633, column: 9
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.callLoaded', file:'file:///data/data/com.permobil.smartdrive.wearos/files/app/vendor.js', line: 34640, column: 14
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.onStart', file:'file:///data/data/com.permobil.smartdrive.wearos/files/app/vendor.js', line: 40793, column: 22
System.err: 	Frame: function:'push../main-activity.js.MainActivity.onStart', file:'file:///data/data/com.permobil.smartdrive.wearos/files/app/vendor.js', line: 53783, column: 25
System.err: 
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1070)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1050)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1042)
System.err: 	at com.permobil.smartdrive.MainActivity.onStart(MainActivity.java:35)
System.err: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
System.err: 	at android.app.Activity.performStart(Activity.java:7165)
System.err: 	at android.app.Activity.performRestart(Activity.java:7276)
System.err: 	at android.app.ActivityThread.handleSleeping(ActivityThread.java:4297)
System.err: 	at android.app.ActivityThread.access$2300(ActivityThread.java:200)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1750)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
System.err: 	at android.os.Looper.loop(Looper.java:193)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6680)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: java.lang.NoSuchMethodError: no non-static method "Landroid/animation/ValueAnimator;.setDuration()V"
```

**Comment by finger563** [comment]
oddly enough the the default is there and seems to work so i'm not sure where the bug is.
